Haveno Performance Report
haveno-dex/haveno-meta pull request #12
Opened 2021-10-27 10:51 UTC by agg505

2021-11-04 16:49 UTC, erciccione commented
ping @agg505

2021-11-16 16:02 UTC, erciccione commented
Ping @agg505.

2021-11-17 03:20 UTC, agg505 commented
@erciccione Fix done, please have a check. And I apologize for no response so long because I just monitored this thread(https://github.com/haveno-dex/haveno/issues/20) instead of this one.

2021-11-17 10:16 UTC, erciccione requested changes
No worries. There are 2 broken links, we can merge after those are fixed.

2021-11-17 10:16 UTC, erciccione commented on haveno-performance-report.md
> +![rmi tcp flame graph](media/performance-report/RMI TCP Connection(*)-127.0.0.1.jpg)
This is not a valid link. Probably better to use a simpler filename, like `rmi-tcp-conn-127.jpg` or something like that.

2021-11-17 10:16 UTC, erciccione commented on haveno-performance-report.md
> +![RMI TCP Connection(idle)](media/performance-report/RMI TCP Connection(idle).jpg)
This is not a valid link. Probably better to use a simpler filename, like `rmi-tcp-conn-idle.jpg` or something like that.

2021-11-17 10:42 UTC, agg505 commented
@erciccione The files now have a better name.

2021-11-19 10:12 UTC, erciccione approved these changes

2021-11-19 10:12 UTC, merged